#!/usr/bin/env bash

# Script for adding vim plugin using vim native plugin manager

# Args: $1=opt or start $2=remote repo url
# Output: Installs the plugin as a git submodule
#         Updates .gitmodules to ignore dirty commits
#         Generates the vim helptags

set -euo pipefail

PLUGIN_PATH=vim/pack/vendor

if [[ $1 != 'opt' && $1 != 'start' ]]; then
    echo -e First arg \"$1\" must be \"start\" or \"opt\" to set where the \
        plugin will be added in path \"$PLUGIN_PATH\" 
    exit 1
fi
plugname=$(basename $2)
plugname="${plugname%.*}"

PLUGIN_PATH=vim/pack/vendor/$1

git submodule add $2 $PLUGIN_PATH/$plugname \
    && git config -f .gitmodules submodule.$PLUGIN_PATH/$plugname.ignore dirty \
    && vim -u NONE -c "helptags $PLUGIN_PATH/$plugname/doc" -c q

