#!/usr/bin/env bash

# Script for removing vim plugin using vim native plugin manager

# Args: $1=plugin_name
# Output: removes the vim plugin submodule

set -euo pipefail

PLUGIN_PATH=vim/pack/vendor

arg_dir=$(dirname $1)
if [[ -d $1 && $arg_dir = $PLUGIN_PATH/opt  || $arg_dir = $PLUGIN_PATH/start ]]; then
    PLUGIN_PATH=$1
elif [[ -d $PLUGIN_PATH/opt/$1 ]]; then
    PLUGIN_PATH=$PLUGIN_PATH/opt/$1
elif [[ -d $PLUGIN_PATH/start/$1 ]]; then
    PLUGIN_PATH=$PLUGIN_PATH/start/$1
else
    echo -e Could not find plugin \"$1\" in path \"$PLUGIN_PATH/opt\" \
        or \"$PLUGIN_PATH/start\"
    exit 1
fi

git submodule deinit -f -- $PLUGIN_PATH \
    && rm -rf .git/modules/$PLUGIN_PATH \
    && git rm -f $PLUGIN_PATH \
    && echo Sucessfully removed plugin \"$1\"
