#!/usr/bin/env bash

# Script for adding vim plugin using vim native plugin manager

# Args: remote repo url
# Output: Installs the plugin as a git submodule
#         Updates .gitmodules to ignore dirty commits
#         Generates the vim helptags

set -euo pipefail

plugname=$(basename $1)
plugname="${plugname%.*}"

GIT_ROOT=$(git rev-parse --show-toplevel)
PLUGIN_PATH=vim/pack/vendor/start

git submodule add $1 $GIT_ROOT/$PLUGIN_PATH/$plugname \
&& git config -f $GIT_ROOT/.gitmodules submodule.$PLUGIN_PATH/$plugname.ignore dirty \
&& vim -u NONE -c "helptags $PLUGIN_PATH/$plugname/doc" -c q

