# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi


#FZF
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# use ripgrep for fzf default
export FZF_DEFAULT_COMMAND='rg --files --no-ignore --hidden --follow --glob "!.git/*"'

export FZF_DEFAULT_OPTS='-m --height=40% --preview="cat {}" --preview-window=right:60%:wrap --border'

# Use fd (https://github.com/sharkdp/fd) instead of the default find
# command for listing path candidates.
_fzf_compgen_path() {
  fd --hidden --follow --exclude ".git" . "$1"
}

# Use fd to generate the list for directory completion
_fzf_compgen_dir() {
  fd --type d --hidden --follow --exclude ".git" . "$1"
}

alias gcob='git branch | fzf | xargs git checkout'

#OH-MY-ZSH
# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

ZSH_THEME="powerlevel10k/powerlevel10k"

# Uncomment the following line to use case-sensitive completion.
CASE_SENSITIVE="false"

# Uncomment the following line to use hyphen-insensitive completion.
# Case-sensitive completion must be off. _ and - will be interchangeable.
HYPHEN_INSENSITIVE="true"

# Uncomment the following line to display red dots whilst waiting for completion.
COMPLETION_WAITING_DOTS="true"

# Add wisely, as too many plugins slow down shell startup.
plugins=(
    golang
    autojump
    git
    zsh-syntax-highlighting
    zsh-autosuggestions
    history-substring-search
    docker
    vi-mode
    zsh-completions
    fzf-tab
)
# For zsh-completions plugin
autoload -U compinit && compinit

source $ZSH/oh-my-zsh.sh

# User configuration

export MANPATH="/usr/local/man:$MANPATH"

# history-substring-search plugin
bindkey -M vicmd 'k' history-substring-search-up
bindkey -M vicmd 'j' history-substring-search-down


# Preferred editor for local and remote sessions
if [[ -n $SSH_CONNECTION ]]; then
    export EDITOR='vim'
else
    export EDITOR='vim'
fi

# Homebrew
export PATH="$(brew --prefix coreutils)/libexec/gnubin:/usr/local/bin:$PATH"

# Postgres.app
export PATH="/Applications/Postgres.app/Contents/Versions/latest/bin:$PATH"

# scipy
export OPENBLAS="$(brew --prefix openblas)"

# pyenv
export PYENV_ROOT="$HOME/.pyenv"

if command -v pyenv 1>/dev/null 2>&1; then
  eval "$(pyenv init -)"
fi

# pyenv-virtualenv
eval "$(pyenv virtualenv-init -)"

# path for pipx packages
export PATH="$PATH:$HOME/.local/bin"
# pipx autocomplete
autoload -U bashcompinit
bashcompinit
eval "$(/usr/local/bin/register-python-argcomplete pipx)"

# pipenv
export PIPENV_VENV_IN_PROJECT=1
export PIPENV_DONT_LOAD_ENV=1 # autoenv handles this
export PIPENV_DEFAULT_PYTHON_VERSION=$(pyenv which python)

# rbenv
eval "$(rbenv init -)"

# gcloud
#golang
export GOPATH=$HOME/code/go
export GOROOT="$(brew --prefix golang)/libexec"
export PATH="$PATH:${GOPATH}/bin:${GOROOT}/bin"

# export JAVA_HOME=$(/usr/libexec/java_home -v 1.8)
# export SBT_OPTS="-XX:+CMSClassUnloadingEnabled -XX:+UseConcMarkSweepGC -XX:ReservedCodeCacheSize=512m -Xss36M -Xms2G -Xmx8G"

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

# direnv
eval "$(direnv hook zsh)"

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/Users/kolaawe/google-cloud-sdk/path.zsh.inc' ]; then . '/Users/kolaawe/google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/Users/kolaawe/google-cloud-sdk/completion.zsh.inc' ]; then . '/Users/kolaawe/google-cloud-sdk/completion.zsh.inc'; fi

